steps:

  - name: "gcr.io/cloud-builders/docker"
    id: "Build da imagem e push para dentro do Container Registry"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ci-golang-tdd:latest", "-f", "./.docker/Dockerfile", "."]
  images: ["gcr.io/$PROJECT_ID/ci-golang-tdd:latest"]

  - id: "Rodando o container"
    name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/ci-golang-tdd:latest"]
