steps:
  - id: "Versão do Go"
    name: "gcr.io/cloud-builders/go"
    args: [ "version" ]
    env: [ "GOPATH=." ]

  # Veja https://github.com/golangci/golangci-lint
  - id: "Corrigindo código"
    name: "golangci/golangci-lint"
    args: [ "golangci-lint","run" ]

  - id: "Rodando Teste"
    name: "gcr.io/cloud-builders/go"
    args: [ "test", "./" ]
    env: [ "GOPATH=." ]

  # Veja: https://rollout.io/blog/put-gosec-pipeline-spot-source-code-security-problems/
  - id: "Detectando problemas de segurança de código-fonte"
    name: "securego/gosec"
    args: [ "src" ]
    env: [ "GOPATH=." ]

  - id: "Construindo a Imagem"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ci-golang-tdd:$SHORT_SHA", "-f", "./.docker/Dockerfile", "."]

  - id: "Subindo da Imagem"
    name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/ci-golang-tdd:$SHORT_SHA" ]
