steps:
  - id: "Build da Imagem"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ci-golang-tdd:$SHORT_SHA", "-f", "./.docker/Dockerfile", "."]

  - id: "Push da Imagem"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ci-golang-tdd:$SHORT_SHA"]

  - id: "Rodando o container"
    name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/ci-golang-tdd:latest"]
